server:
  port: 8080

spring:
  application:
    name: crud-practice
  datasource:
    url: "jdbc:mysql://localhost:3306/swp391_db_releasee"
    username: root
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mvc:
    converters:
      preferred-json-mapper=gson:

  mail:
    host: smtp.gmail.com
    port: 587
    username: thanhdhde170795@gmail.com
    password: thanh20032003
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true