server:
  port: 8080

spring:
  application:
    name: Wall-E
  datasource:
    url: "jdbc:mysql://localhost:3306/swp391_db_releasee"
    username: root
    password: Thanh20032003@

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 465
    username: thanhdhde170795@fpt.edu.vn
    password: bdmt kdvd kbpx zzfd
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true,
            required: true
          ssl:
            enable: true



payment:
  vnPay:
    url: ${PAY_URL}
    tmnCode: ${TMN_CODE}
    secretKey: ${SECRET_KEY}
    returnUrl: ${RETURN_URL}
    version: ${VERSION}
    command: ${COMMAND}
    orderType: ${ORDER_TYPE}
